### ISSUE TITLE
New Bamboo Build breaks this plugin.

### ISSUE THREAD

**Issue by TeeriaLLC** [Zaicon/InfiniteChests#1]
[09/12/15 10:03:55] [Server API] Warning: Plugin "InfiniteChests" has had an unhandled exception thrown by one of its NetGetData handlers: 
System.MissingFieldException: Field not found: 'Terraria.Main.tile'.
   at InfiniteChests.InfiniteChests.OnGetData(GetDataEventArgs e)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

**Comment by TeeriaLLC** [comment]
Nevermind, this seems to be a Bamboo issue that should be fixed soon.
