### ISSUE TITLE
Serverlog Error.

### ISSUE THREAD

**Issue by TeeriaLLC** [Zaicon/InfiniteChests#2]
Found this in my log lately, do not know what causes it and what it actually breaks. Although it obviously has to do with placing of the chest.

[02/17/16 09:40:16] [Server API] Warning: Plugin "InfiniteChests" has had an unhandled exception thrown by one of its NetGetData handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Chest.CreateChest(Int32 X, Int32 Y, Int32 id)
   at Terraria.WorldGen.PlaceChest(Int32 x, Int32 y, UInt16 type, Boolean notNearOtherChests, Int32 style)
   at InfiniteChests.InfiniteChests.OnGetData(GetDataEventArgs e)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

**Comment by Zaicon** [comment]
Hey there,
Are you still getting this issue?
